title: Schritt fÃ¼r Schritt zum eigenen OER
subtitle:
email: nele@ebildungslabor.de
twitter: https://twitter.com/eBildungslabor
chat: https://chat.mozillafoundation.org/mozilla/channels/mozfest-open-projects
description: > # this means to ignore newlines until "baseurl:"
  Does your MozFest session involve hands-on, project based learning? This
  training is for anyone running an open project at MozFest. This can be
  software, curriculum, or anything you can build together with a group.
baseurl: "/open-leadership-training-series" # the subpath of your site, e.g. /blog
url: "https://mozilla.github.io" # the base hostname & protocol for your site
github:
  repo: "ebildungslabor/make-your-oer"
  branch: "gh-pages"


collections:
  articles:
    output: true
permalink: /:path/

# Build settings
markdown: kramdown

redcarpet:
    extensions: [
        'no_intra_emphasis',
        'fenced_code_blocks',
        'autolink',
        'strikethrough',
        'superscript',
        'with_toc_data',
        'tables',
        'hardwrap'
    ]

# variables
video: "<span class=\"video-player\"></span>"
assignment: "<span class=\"assignment\">Assignment: </span>"
